services:
  - telegram:
    - video_call:
        - l3_layer: 'udp'
        - avg_bitrate: 500-1000
        - avg_pkt_size: 100-500
    - audio_call:
        - l3_layer: 'udp'
        - avg_bitrate: 100-500
        - avg_pkt_size: 0-100
