services:
  - UDP:
    - telegram:
      - video_call:
          avg_bitrate: [207938, 1132351]
          avg_pkt_size: [312, 936]
      - audio_call:
          avg_bitrate: [29850, 57131]
          avg_pkt_size: [134, 251]
